# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QCheckBox, QRadioButton, QMenu, QAction

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QApplication, QDesktopWidget, QGroupBox,
                             QGridLayout, QTextBrowser, QVBoxLayout, QFormLayout,
                             QLabel, QPushButton, QComboBox, QCheckBox, QTextEdit,
                             QLineEdit, QHBoxLayout)

class Ui_Dialog(QWidget):

    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # mainWindow = QMainWindow()
        #
        # win=SerialAssistant()
        # win.setupUi(mainWindow)
        # mainWindow.show()


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(594, 473)
        self.serial_group = QtWidgets.QGroupBox(Dialog)
        self.serial_group.setGeometry(QtCore.QRect(10, 10, 241, 331))
        self.serial_group.setObjectName("serial_group")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.serial_group)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")


        #串口检测按钮
        self.serialcheck_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.serialcheck_button.setObjectName("serialcheck_button")




        self.gridLayout.addWidget(self.serialcheck_button, 0, 1, 1, 1)
        self.serail_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.serail_label.setObjectName("serail_label")
        self.gridLayout.addWidget(self.serail_label, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)



        #显示可用串口
        self.serialchoose_box = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.serialchoose_box.setObjectName("serialchoose_box")
        self.verticalLayout_2.addWidget(self.serialchoose_box)



        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")



        #停止位
        self.tingzhiwei = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tingzhiwei.setObjectName("tingzhiwei")
        self.gridLayout_2.addWidget(self.tingzhiwei, 3, 0, 1, 1)
        self.tingzhiwei_button = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tingzhiwei_button.addItems(['1', '1.5', '2'])
        self.tingzhiwei_button.setObjectName("tingzhiwei_button")
        self.gridLayout_2.addWidget(self.tingzhiwei_button, 3, 1, 1, 1)

        #校验位
        self.jiaoyanwei_button = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.jiaoyanwei_button.addItems(['N', 'E', 'O'])# 校验位N－无校验，E－偶校验，O－奇校验
        self.jiaoyanwei_button.setObjectName("jiaoyanwei_button")
        self.gridLayout_2.addWidget(self.jiaoyanwei_button, 2, 1, 1, 1)
        self.jiaoyanwei = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.jiaoyanwei.setObjectName("jiaoyanwei")
        self.gridLayout_2.addWidget(self.jiaoyanwei, 2, 0, 1, 1)

        #数据位
        self.shujuwei_button = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.shujuwei_button.addItems(['8', '7', '6', '5'])
        self.shujuwei_button.setObjectName("shujuwei_button")
        self.shujuwei = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.shujuwei.setObjectName("shujuwei")
        self.gridLayout_2.addWidget(self.shujuwei, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.shujuwei_button, 1, 1, 1, 1)

        #波特率
        self.botelv = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.botelv.setObjectName("botelv")
        self.gridLayout_2.addWidget(self.botelv, 0, 0, 1, 1)
        self.botelv_botton = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.botelv_botton.addItems(['100', '300', '600', '1200', '2400', '4800', '9600', '14400', '19200',
                          '38400', '56000', '57600', '115200', '128000', '256000'])
        self.botelv_botton.setObjectName("botelv_botton")




        self.gridLayout_2.addWidget(self.botelv_botton, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)


        #打开串口
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.message_group = QtWidgets.QGroupBox(Dialog)
        self.message_group.setGeometry(QtCore.QRect(10, 350, 331, 111))
        self.message_group.setObjectName("message_group")
        self.lineEdit = QtWidgets.QLineEdit(self.message_group)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 191, 81))
        self.lineEdit.setObjectName("lineEdit")
        self.message_send = QtWidgets.QPushButton(self.message_group)
        self.message_send.setGeometry(QtCore.QRect(210, 80, 111, 23))
        self.message_send.setObjectName("message_send")
        self.message_clean = QtWidgets.QPushButton(self.message_group)
        self.message_clean.setGeometry(QtCore.QRect(210, 50, 111, 23))
        self.message_clean.setObjectName("message_clean")
        self.hex_check = QtWidgets.QCheckBox(self.message_group)
        self.hex_check.setGeometry(QtCore.QRect(220, 20, 91, 21))
        self.hex_check.setObjectName("hex_check")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(360, 260, 211, 198))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.servo_group = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.servo_group.setContentsMargins(0, 0, 0, 0)
        self.servo_group.setObjectName("servo_group")
        self.servoslider_2 = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.servoslider_2.setOrientation(QtCore.Qt.Horizontal)
        self.servoslider_2.setObjectName("servoslider_2")
        self.servo_group.addWidget(self.servoslider_2, 1, 1, 1, 1)
        self.servoslider_1 = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.servoslider_1.setOrientation(QtCore.Qt.Horizontal)
        self.servoslider_1.setObjectName("servoslider_1")
        #设置左右最大值
        # self.servoslider_1.setMinimum(500)
        # self.servoslider_1.setMaximum(2000)
        # 假设舵机滑块对象的命名是 servoslider_1, servoslider_2, ..., servoslider_6
        # for i in range(1, 7):
        #     slider = getattr(self, f"servoslider_{i}")
        #     slider.setMinimum(500)
        #     slider.setMaximum(2000)
        # 设置第一个舵机的最小值和最大值


        self.servo_group.addWidget(self.servoslider_1, 0, 1, 1, 1)
        self.servoslider_3 = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.servoslider_3.setOrientation(QtCore.Qt.Horizontal)
        self.servoslider_3.setObjectName("servoslider_3")
        self.servo_group.addWidget(self.servoslider_3, 2, 1, 1, 1)
        self.servolabel_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.servolabel_4.setObjectName("servolabel_4")
        self.servo_group.addWidget(self.servolabel_4, 3, 2, 1, 1)
        self.servolabel_1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.servolabel_1.setObjectName("servolabel_1")
        self.servo_group.addWidget(self.servolabel_1, 0, 2, 1, 1)
        self.servoslider_6 = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.servoslider_6.setOrientation(QtCore.Qt.Horizontal)
        self.servoslider_6.setObjectName("servoslider_6")
        self.servo_group.addWidget(self.servoslider_6, 5, 1, 1, 1)
        self.servolabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.servolabel_2.setObjectName("servolabel_2")
        self.servo_group.addWidget(self.servolabel_2, 1, 2, 1, 1)
        self.servoslider_4 = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.servoslider_4.setOrientation(QtCore.Qt.Horizontal)
        self.servoslider_4.setObjectName("servoslider_4")
        self.servo_group.addWidget(self.servoslider_4, 3, 1, 1, 1)
        self.servolabel_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.servolabel_5.setObjectName("servolabel_5")
        self.servo_group.addWidget(self.servolabel_5, 4, 2, 1, 1)
        self.servoslider_5 = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.servoslider_5.setOrientation(QtCore.Qt.Horizontal)
        self.servoslider_5.setObjectName("servoslider_5")
        self.servo_group.addWidget(self.servoslider_5, 4, 1, 1, 1)
        self.servolabel_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.servolabel_3.setObjectName("servolabel_3")
        self.servo_group.addWidget(self.servolabel_3, 2, 2, 1, 1)
        self.servolabel_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.servolabel_6.setObjectName("servolabel_6")
        self.servo_group.addWidget(self.servolabel_6, 5, 2, 1, 1)
        self.servodisplay_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.servodisplay_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.servodisplay_1.setObjectName("servodisplay_1")
        self.servo_group.addWidget(self.servodisplay_1, 0, 0, 1, 1)
        self.servodisplay_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.servodisplay_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.servodisplay_2.setObjectName("servodisplay_2")
        self.servo_group.addWidget(self.servodisplay_2, 1, 0, 1, 1)
        self.servodisplay_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.servodisplay_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.servodisplay_3.setObjectName("servodisplay_3")
        self.servo_group.addWidget(self.servodisplay_3, 2, 0, 1, 1)
        self.servodisplay_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.servodisplay_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.servodisplay_4.setObjectName("servodisplay_4")
        self.servo_group.addWidget(self.servodisplay_4, 3, 0, 1, 1)
        self.servodisplay_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.servodisplay_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.servodisplay_5.setObjectName("servodisplay_5")
        self.servo_group.addWidget(self.servodisplay_5, 4, 0, 1, 1)
        self.servodisplay_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.servodisplay_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.servodisplay_6.setObjectName("servodisplay_6")
        self.servo_group.addWidget(self.servodisplay_6, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


        # self.servoslider_1.setMinimum(500)
        # self.servoslider_1.setMaximum(2000)
        #
        # # 设置第二个舵机的最小值和最大值
        # self.servoslider_2.setMinimum(500)
        # self.servoslider_2.setMaximum(2000)
        #
        # # 设置第三个舵机的最小值和最大值
        # self.servoslider_3.setMinimum(500)
        # self.servoslider_3.setMaximum(2000)
        #
        # # 设置第四个舵机的最小值和最大值
        # self.servoslider_4.setMinimum(500)
        # self.servoslider_4.setMaximum(2000)
        #
        # # 设置第五个舵机的最小值和最大值
        # self.servoslider_5.setMinimum(500)
        # self.servoslider_5.setMaximum(2000)
        #
        # # 设置第六个舵机的最小值和最大值
        # self.servoslider_6.setMinimum(500)
        # self.servoslider_6.setMaximum(2000)
        # 假设舵机滑块对象的命名是 servoslider_1, servoslider_2, ..., servoslider_6
        for i in range(1, 7):
            slider = getattr(self, f"servoslider_{i}")
            slider.setMinimum(500)
            slider.setMaximum(2000)
        self.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.serial_group.setTitle(_translate("Dialog", "串口设置"))
        self.serialcheck_button.setText(_translate("Dialog", "检查串口"))
        self.serail_label.setText(_translate("Dialog", "串口选择"))
        self.tingzhiwei.setText(_translate("Dialog", "停止位"))
        self.botelv.setText(_translate("Dialog", "波特率"))
        self.shujuwei.setText(_translate("Dialog", "数据位"))
        self.jiaoyanwei.setText(_translate("Dialog", "校验位"))
        self.pushButton_2.setText(_translate("Dialog", "打开串口"))
        self.message_group.setTitle(_translate("Dialog", "信息发送"))
        self.message_send.setText(_translate("Dialog", "发送"))
        self.message_clean.setText(_translate("Dialog", "清除"))
        self.hex_check.setText(_translate("Dialog", "   hex发送"))
        self.servolabel_4.setText(_translate("Dialog", "舵机4"))
        self.servolabel_1.setText(_translate("Dialog", "舵机1"))
        self.servolabel_2.setText(_translate("Dialog", "舵机2"))
        self.servolabel_5.setText(_translate("Dialog", "舵机5"))
        self.servolabel_3.setText(_translate("Dialog", "舵机3"))
        self.servolabel_6.setText(_translate("Dialog", "舵机6"))
